apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: 5i5j
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-get-service-ip
    image: yanzhi/k8s-net
    command: ['dotnet', 'k8s-net.dll', 'exservice']
    volumeMounts:
    - mountPath: /data/
      name: config
  #   image: busybox:1.28
  #   command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'cat /data/dubbo-env && source /data/dubbo-env && echo $DUBBO && echo The app is running! && sleep 3600']
    volumeMounts:
    - mountPath: /data/
      name: config       
  volumes:
  - emptyDir: {}
    name: config