name: Publish Docker Image to GitHub 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker Images to GPR
      uses: machine-learning-apps/gpr-docker-publish@v1.4
      id: docker
      with:
        IMAGE_NAME: 'k8s-net'
        TAG: 'latest'
        DOCKERFILE_PATH: './Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
